
extrn detectscr :near,initscr  :near,clrscr   :near,clreol   :near
extrn delline   :near,insline  :near,setcolor :near
extrn getcolor  :near,defwindow:near,askwindow:near
extrn selwindow :near,putframe :near,delframe :near
extrn scrollup  :near,scrolldn :near,scrolllf :near
extrn scrollrg  :near,gotoxy   :near,getxy    :near,print   :near
extrn convstring:near,readkey  :near,flush    :near,input   :near
extrn deletestr :near,insertstr:near,copystr  :near
extrn concatstr :near,posstr   :near,upstr    :near,ignchar :near
extrn cutchar   :near,partostr :near,dadd     :near
extrn dsub    :near
extrn dmul      :near
extrn ddiv     :near
extrn dneg     :near
extrn numtostr:near
extrn strtonum  :near
